### ISSUE TITLE
Slash Commands Missing Access to register! 

### ISSUE THREAD

**Issue by Fluffyacid** [Tomato6966/Discord-js-handler-slash-Commands#1]
Bot have all Permission in Server and Discord Developer

 [antiCrash] :: Unhandled Rejection/Catch
DiscordAPIError[50001]: Missing Access
    at SequentialHandler.runRequest (D:\Coding\PENGUINE-TOOLS\Penguine\Slash\Discord-js-handler-slash-Commands-main\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.js:198:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (D:\Coding\PENGUINE-TOOLS\Penguine\Slash\Discord-js-handler-slash-Commands-main\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.js:99:20) {
  rawError: { message: 'Missing Access', code: 50001 },
  code: 50001,
  status: 403,
  method: 'put',
  url: 'https://discord.com/api/v9/applications/879021981243174933/guilds/875903965114552361/commands'
} Promise {
  <rejected> DiscordAPIError[50001]: Missing Access
      at SequentialHandler.runRequest (D:\Coding\PENGUINE-TOOLS\Penguine\Slash\Discord-js-handler-slash-Commands-main\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.js:198:23)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async SequentialHandler.queueRequest (D:\Coding\PENGUINE-TOOLS\Penguine\Slash\Discord-js-handler-slash-Commands-main\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.js:99:20) {
    rawError: { message: 'Missing Access', code: 50001 },
    code: 50001,
    status: 403,
    method: 'put',
    url: 'https://discord.com/api/v9/applications/879021981243174933/guilds/875903965114552361/commands'
  }
}

**Comment by Tomato6966** [comment]
The Bot is missing access for allowing slash cmds

you did not invite the bot with the application.commands skope

Example Invite Link:
`https://discord.com/api/oauth2/authorize?client_id=CLIENTID&permissions=8&scope=bot%20applications.commands`
Replace `CLIENTID` with your actual client id, in code it could look like that:
```
let inviteLink = `https://discord.com/api/oauth2/authorize?client_id=${client.user.id}&permissions=8&scope=bot%20applications.commands`
```
