### ISSUE TITLE
antiCrash?

### ISSUE THREAD

**Issue by MegaTKC** [Tomato6966/Discord-js-handler-slash-Commands#2]
|| <==> || [Wed Sep 01 2021 19:47:21] || <==> || Shard #0 Disconnected || <==> ||
 [antiCrash] :: Unhandled Rejection/Catch
Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/pi/Discord-js-handler-slash-Commands/node_modules/discord.js/src/client/websocket/WebSocketManager.js:244:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.login (/home/pi/Discord-js-handler-slash-Commands/node_modules/discord.js/src/client/Client.js:245:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'
} Promise {
  <rejected> Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
      at WebSocketManager.createShards (/home/pi/Discord-js-handler-slash-Commands/node_modules/discord.js/src/client/websocket/WebSocketManager.js:244:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Client.login (/home/pi/Discord-js-handler-slash-Commands/node_modules/discord.js/src/client/Client.js:245:7) {
    [Symbol(code)]: 'DISALLOWED_INTENTS'
  }
}

**Comment by Tomato6966** [comment]
Read the error and understand
your intents are privilaged intents but u didint enable them in discord.com/developers
